Remove sufix "es"
KorzhCom/EasyData pull request #157
Opened 2022-11-15 19:20 UTC by Alerinos

Adding a sufix to the end of each table name looks very bad. More information is described here. https://github.com/KorzhCom/EasyData/issues/153
I don't think this is a needed feature (even my client laughed about it when he asked me if I was exaggerating).
Alternatively, you can make settings

2022-12-10 13:25 UTC, antifree commented
Hello!
Thank you for the contribution and sorry for answering lately. Could you please add an option for this change? I think it depends on the use-case to use plural form so singular

2022-12-10 18:30 UTC, tombohub requested changes
no shortcuts

2023-02-01 08:07 UTC, Alerinos commented
@antifree 
It seems to me that it shouldn't be, if someone wants to use their own name, they will use this:
```cs
[Display(Name = "HashTags", Description = "List of tags in the article")]
public class HashTag { ... }
```

2023-03-23 13:42 UTC, Alerinos commented
@eqteamlead @antifree We can make such a simple change and let the programmer decide how we want to name the model?

2024-02-03 12:15 UTC, korzh reviewed
We won't apply this change. The name of the property says exactly what it means (NamePlural). If you need the original entity name there is just the Name property for that.

2024-02-03 12:18 UTC, korzh commented
We don't accept this change. If you need to show the original (not plural) names for each entity - there is `usePluralNames` property of EasyDataViewDispatcher and RootDataView. So, you can simply set that option to `false`:

```
new EasyDataViewDispatcher({
    endpoint: '/api/easydata',
    usePluralNames: false
}).run();
```

2024-02-03 12:18 UTC, closed without merging