Add help text to the fields
KorzhCom/EasyData pull request #71
Opened 2021-11-16 11:01 UTC by vasiliy-chefonov

Hey) I suggest adding a help text from the properties description to the fields in the grid and entity editing form. What do you think about it?

![image](https://user-images.githubusercontent.com/81791194/141973181-520ada7f-5ffe-408c-ab93-346daa8c657f.png)
![image](https://user-images.githubusercontent.com/81791194/141973196-4e877769-9e29-45cd-8780-d5ea9468ce59.png)
![image](https://user-images.githubusercontent.com/81791194/141973211-4f54a433-563d-441a-be1d-b18fec8087a1.png)

2021-11-16 22:09 UTC, antifree commented on easydata.js/packs/crud/src/form/entity_form_builder.ts
> +        let fieldHolder = parent.lastChild as HTMLElement;
It is better to replace this code:

```ts
    domel(parent)
            .addChild('label', b => b
                .attr('for', attr.id)
                .addHtml(`${attr.caption} ${required ? '<sup style="color: red">*</sup>' : ''}: `)
            ).addChild('div');

  let fieldHolder = parent.lastChild as HTMLElement;
```

with this 

```ts
  domel(parent)
          .addChild('label', b => b
              .attr('for', attr.id)
              .addHtml(`${attr.caption} ${required ? '<sup style="color: red">*</sup>' : ''}: `)
          );
          
  const fieldSlot = domel('div', parent).toDOM()
```

2021-11-16 22:11 UTC, antifree commented on easydata.js/packs/crud/src/form/entity_form_builder.ts
> +            domel(fieldHolder).addChild('small', b => b
I'm not sure about adding the here description. Because in the future we probably add error text under inputs. Maybe it would be better to use the quesion-mark approach as in the grid, what do you think  @korzh ?

2021-11-16 22:13 UTC, antifree commented
At all, LGTM 🔥

2021-11-16 22:20 UTC, antifree commented on easydata.js/packs/core/src/data/data_column.ts
> +    description: string | null;
I think it is better to use short-form `desc` for the Descriptor

2021-11-16 22:21 UTC, antifree commented on easydata.net/src/EasyData.Core/EasyDataResultSet.cs
> +        [JsonProperty("description")]
Same here. `desc`

2021-11-16 22:24 UTC, antifree commented
At all, LGTM 🔥

2021-12-03 08:32 UTC, vasiliy-chefonov commented
@korzh Hey) I have some more changes I am ready to propose. Can you review this PR, please?

2021-12-04 17:41 UTC, korzh requested changes
Please fix the spelling errors I've added the fixes for (in data_column.ts and EasyDataResultSet.cs files).

2021-12-07 16:59 UTC, antifree approved these changes

2021-12-08 08:53 UTC, korzh approved these changes
We still have a few grammars mistakes but I will fix them in the dev.

2021-12-08 08:54 UTC, merged