[Upd] Update API to pass key values in the body or query parameters
KorzhCom/EasyData pull request #77
Opened 2021-12-12 15:46 UTC by antifree

Currently, we pass key values in the URL which is not convenient where there are several key fields.
I have updated API to read key values from the body in POST and from query parameters in GET requests.

2021-12-14 12:24 UTC, korzh requested changes
I have added several comments to the changed files. Some of them require further discussion I think.

2021-12-14 12:24 UTC, korzh commented on easydata.js/packs/crud/src/form/entity_form_builder.ts
> +                                        const attr = lookupEntity.attributes.filter(attr => attr.isPrimaryKey)[0];
I think it's better to add a special function for that (like `getPrimaryAttr()`).

2021-12-14 12:24 UTC, korzh commented on easydata.js/packs/crud/src/form/entity_form_builder.ts
> +                                        this.context.getEntity({[key]: selectedValue}, lookupEntity.id)
I would like to rename all those procedures as `getEntityRecord()`, `updateEntityRecord`, `deleteEntityRecord`, etc.

And it's better to pass an object to such functions so we will not need to make any changes in functions' signatures in the future. We will just change the interface (add or delete some fields, etc).

2021-12-14 12:24 UTC, korzh commented on easydata.js/packs/crud/src/main/data_context.ts
>          this.setEnpointIfNotExist('GetEntities', combinePath(endpointBase, 'models/{modelId}/crud/{entityId}/fetch'));
We need to sync the names of endpoints with the ones used on the server-side (GetDataset, GetRecord, CreateRecord, UpdateRecord, DeleteRecord). The term "Entity" is so confusing so we need to be more unambiguous

2021-12-14 12:24 UTC, korzh commented on easydata.net/src/EasyData.AspNetCore/Middleware/EasyDataMiddleware.cs
> +                new Endpoint(DataAction.FetchRecord, @"^/models/([^/]+?)/crud/([^/]+?)/fetch$", "GET"),
Maybe it would be more convenient if we place the entity type name in the request body as well? 
We need to consider all pros and cons of such an approach.

2021-12-14 12:24 UTC, korzh commented on easydata.net/test/EasyData.AspNetCore.Tests/EasyDataMiddlewareTests.cs
> +        public async Task EasyData_DeleteEntity(string endpoint, string entity, string keyPropery, string entityId)
It's better to change the names of test functions so they describe what they do and what results we expect.

For example, DeleteEntityRecord_should_return_OK

2021-12-14 17:11 UTC, antifree commented on easydata.net/src/EasyData.AspNetCore/Middleware/EasyDataMiddleware.cs
> +                new Endpoint(DataAction.FetchRecord, @"^/models/([^/]+?)/crud/([^/]+?)/fetch$", "GET"),
I'm not sure. It is covinient for the library, but in this case users wiil have different contract based on passed entitiy type. I think it is not good for api

2021-12-21 21:29 UTC, antifree commented on easydata.net/src/EasyData.AspNetCore/Middleware/EasyDataMiddleware.cs
> +                new Endpoint(DataAction.FetchRecord, @"^/models/([^/]+?)/crud/([^/]+?)/fetch$", "GET"),
Let's discuss it and create a separate MR if it will be needed. I'll resolve for now

2021-12-21 21:47 UTC, antifree commented on easydata.net/test/EasyData.AspNetCore.Tests/EasyDataMiddlewareTests.cs
> +        public async Task EasyData_DeleteEntity(string endpoint, string entity, string keyPropery, string entityId)
Done

2021-12-21 21:47 UTC, antifree commented on easydata.js/packs/crud/src/main/data_context.ts
>          this.setEnpointIfNotExist('GetEntities', combinePath(endpointBase, 'models/{modelId}/crud/{entityId}/fetch'));
Done

2021-12-21 21:47 UTC, antifree commented on easydata.js/packs/crud/src/form/entity_form_builder.ts
> +                                        const attr = lookupEntity.attributes.filter(attr => attr.isPrimaryKey)[0];
Done

2021-12-22 12:05 UTC, korzh approved these changes

2021-12-22 17:41 UTC, merged